name: "airmen_file_uploaded"
pack: "cws_inform"
description: "Receive incoming webhook when readiness files uploaded to S3"
enabled: true

trigger:
    type: "core.st2.CronTimer"
    parameters:
        timezone: "UTC"
        minute: "*/2"

action:
    ref: "cws_inform.update_airmen"