name: "inventory_request_submitted"
pack: "cws_inform"
description: "Receive incoming webhook when inventory request submitted"
enabled: true

trigger:
    type: "core.st2.webhook"
    parameters:
        url: "snow/inventory_request"

criteria:
    trigger.body.name:
        type: "equals"
        pattern: "inventory_request"

action:
    ref: "cws_inform.submit_request"
    parameters:
        sys_id: "{{trigger.body.sys_id}}"